### ISSUE TITLE
As an administrator, I want to organize questions so I can find them easily in the future

### ISSUE THREAD

**Issue by rortiz9** [ra4king/JuniorDesign-ActiveLearning#12]
## Story/Task Details
- [x] Design a user generated tagging system
- [x] Extend database to handle tag data for questions
- [x] Implement UI features to create, edit, and search by tags
- [x] Implement folder hierarchy for questions

## Acceptance Scenarios
Given: user added a tag
When: user creates or edits a question
Then: the tag is stored along with the question in the database

Given: user requested tagged questions
When: user creates or edits a quiz
Then: the server sends a list of questions containing the tag

## Done Done Criteria
Tagging has been tested on both new and existing questions. Search by tag has been tested for multiple different tags.

**Comment by Shazambom** [comment]
UI creation of tags complete.
