### ISSUE TITLE
As an administrator, I want to compare statistics between previous semesters so I can measure differences in teaching techniques. 

### ISSUE THREAD

**Issue by josephcantrell14** [ra4king/JuniorDesign-ActiveLearning#14]
## Story/Task Details
- [x] Track cumulative responses for a question
- [x] Utilize a graphing library for viewing multiple statistics
- [ ] Implement viewing multiple semesters' statistics through the UI

## Acceptance Scenarios
Given: administrator has logged in to the site
When: administrator views total statistics for a question across multiple semesters
Then: the response statistics for a question are displayed for multiple semesters

## Done Done Criteria
Correct statistics across semesters are displayed for each individual question.

**Comment by Shazambom** [comment]
Statistics I need from the back-end:
Question id
Question Name
Question Topic
Number correct for question
Number incorrect for question
Number picked A
Number picked B
Number picked C
Number picked D

**Comment by Shazambom** [comment]
Statistics are up and running. Fully functional. Unfortunately this will not work across semesters just yet due to this not being implemented yet. That feature will likely be implemented in a later sprint.

**Comment by Shazambom** [comment]
We are dealing with different semesters at a later sprint.
