### ISSUE TITLE
As a student, I want to see my performance throughout the semester so I can self-evaluate and improve.

### ISSUE THREAD

**Issue by josephcantrell14** [ra4king/JuniorDesign-ActiveLearning#15]
## Story/Task Details
- [x] Track individual students' responses to questions
- [x] Utilize a graphing library for viewing statistics
- [x] Implement viewing personal statistics through the UI

## Acceptance Scenarios
Given: student has logged in to the site
When: student views statistics for a particular question
Then: the response statistics for a particular question is displayed

## Done Done Criteria
Correct response statistics are displayed for each individual question.

**Comment by Shazambom** [comment]
All have been completed.
